- name: Install Base Python APT Packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip

- name: Install Other Python APT Packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-venv
      - python3-poetry