echo "UPLOAD_LOCATION=$ANSIBLE_IMMICH_UPLOAD_LOCATION" > .env
echo "DB_DATA_LOCATION=$ANSIBLE_IMMICH_DB_DATA_LOCATION" >> .env
echo "TZ=$ANSIBLE_IMMICH_TZ" >> .env
echo "IMMICH_VERSION=$ANSIBLE_IMMICH_VERSION" >> .env
echo "DB_PASSWORD=$ANSIBLE_IMMICH_DB_PASSWORD" >> .env
echo "DB_USERNAME=$ANSIBLE_IMMICH_DB_USERNAME" >> .env
echo "DB_DATABASE_NAME=$ANSIBLE_IMMICH_DB_DATABASE_NAME" >> .env
echo "EXTERNAL_UPLOAD_LOCATION=$ANSIBLE_IMMICH_EXTERNAL_UPLOAD_LOCATION" >> .env

mkdir -p ${ANSIBLE_IMMICH_DB_DATA_LOCATION}