echo "MEDIA_LIBRARY=${ANSIBLE_JF_MEDIA_LIBRARY}" >> .env
echo "CONFIG_LOCATION=${ANSIBLE_JF_CONFIG_LOCATION}" >> .env
echo "CACHE_LOCATION=${ANSIBLE_JF_CACHE_LOCATION}" >> .env

mkdir -p ${ANSIBLE_JF_CONFIG_LOCATION}
mkdir -p ${ANSIBLE_JF_CACHE_LOCATION}