---
- name: Make Temp Directory
  ansible.builtin.file:
    path: /tmp/linux-setup
    state: directory

- name: Update APT Cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: APT Upgrade
  become: true
  ansible.builtin.apt:
    upgrade: "yes"

- name: Install Docker Keyring
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Common APT Packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - openjdk-8-jdk
      - openjdk-17-jdk
      - vim
      - tmux
      - git
      - yt-dlp
      - unzip
      - htop
      - curl
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin


- name: Updating Global Git Email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Updating Global Git Username
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: Generate SSH Key (ed25519)
  community.crypto.openssh_keypair:
    path: "{{ home_dir }}/.ssh/id_ssh_ed25519"
    type: ed25519

- name: Install TailScale
  ansible.builtin.shell:
    "curl -fsSL https://tailscale.com/install.sh | sh"