echo "NEXTCLOUD_LIBRARY=$ANSIBLE_NX_NEXTCLOUD_LIBRARY" >> .env
echo "DB_DATA_LOCATION=$ANSIBLE_NX_DB_DATA_LOCATION" >> .env
echo "DB_ROOT_PW=$ANSIBLE_NX_DB_ROOT_PW" >> .env
echo "DB_USER=$ANSIBLE_NX_DB_USER" >> .env
echo "DB_PW=$ANSIBLE_NX_DB_PW" >> .env
echo "TRUSTED_DOMAINS=$ANSIBLE_NX_TRUSTED_DOMAINS" >> .env

mkdir -p ${ANSIBLE_NX_DB_DATA_LOCATION}